version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - 127.0.0.1:15432:5432/tcp
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    restart: always
  redis:
    image: redis:6
    command: redis-server --requirepass test
    ports:
      - 127.0.0.1:16379:6379/tcp
    restart: always

  influxdb:
    image: influxdb:2.1
    ports:
      - 127.0.0.1:18086:8086/tcp
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=test1234
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=test
    restart: always
  telegraf:
    image: telegraf:1.22
    ports:
      - 127.0.0.1:18125:8125/udp
    volumes:
      - ./telegraf-test.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
