version: '3.7'
services:
  immudb:
    image: codenotary/immudb:1.3
    ports:
      - "127.0.0.1:3322:3322/tcp"
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:9497:9497/tcp"
    restart: always
  redis:
    image: redis:6
    command: redis-server --requirepass test
    ports:
      - "127.0.0.1:6379:6379/tcp"
    restart: always

  influxdb:
    image: influxdb:2.1
    ports:
      - "127.0.0.1:8086:8086/tcp"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=test1234
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=test
    restart: always
  telegraf:
    image: telegraf:1.22
    ports:
      - "127.0.0.1:8125:8125/udp"
    volumes:
      - ./telegraf-test.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
