version: '3.5'
services:
  immudb:
    image: codenotary/immudb:1.3
    networks:
      - integration
  redis:
    image: redis:6
    command: redis-server --requirepass test
    networks:
      - integration

networks:
  integration:
    name: ${NETWORK_NAME}